name: Build

on: [push]

jobs:

  test:
    runs-on: ubuntu-18.04

    strategy:
        fail-fast: true
        matrix:
          php: [7.4, 8.0]

    name: PHP ${{ matrix.php }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, redis, memcached
        tools: composer:v2
        coverage: xdebug

    - name: Cache PHP dependencies
      uses: actions/cache@v1
      with:
       path: ~/.composer
       key: composer-${{ hashFiles('**/composer.json') }}

    - name: Validate composer and install dependecies
      run: composer validate && composer update --prefer-dist --no-interaction --no-progress

    - name: PHPStan
      run: vendor/bin/phpstan analyse src

    - name: PHPCS
      run: vendor/bin/phpcs --standard=standard.xml src

    - name: PHPUnit
      run: vendor/bin/phpunit -c phpunit.xml

    - name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v1
      with:
       file: build/clover.xml
       flags: unittests
       name: codecov-umbrella
       fail_ci_if_error: true